[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "binaryoptionstoolsv2"
version = "0.1.0"

[tool.setuptools]
packages = ["BinaryOptionsToolsV2"]

