[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hiddencloud"
version = "0.2.0"
description = "hiddencloud arm build"

[tool.setuptools]
packages = ["hiddencloud"]

